kind: Secret
apiVersion: v1
metadata:
  name: todo-web-secret
  labels:
    kiamol: ch12
type: Opaque
stringData:
  secrets.json: |-
    {
      "ConnectionStrings": {
        "ToDoDb": "Server=todo-db;Database=todo;User Id=postgres;Password=kiamol-2*2*;"
      }
    }