kind: Namespace
apiVersion: v1
metadata:
  name: kiamol-ch14-test
  labels:
    kiamol: ch14
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: timecheck
  namespace: kiamol-ch14-test
  labels:
    kiamol: ch14
spec:
  selector:
    matchLabels:
      app: timecheck
  template:
    metadata:
      labels:
        app: timecheck
    spec:
      containers:
        - name: timecheck
          image: kiamol/ch07-timecheck
          env:
            - name: Metrics__Enabled
              value: "true"
          ports:
            - containerPort: 8080
              name: metrics
