x-zk-image: &zk-image zookeeper:3.8.1

version: '3.8'

services:
  zoo1:
    image: *zk-image
    restart: always
    container_name: zoo1
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 observerMasterPort=2889
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog

  zoo2:
    image: *zk-image
    restart: always
    container_name: zoo2
    ports:
      - "2182:2181"
      - "2889:2888"
      - "3889:3888"
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 observerMasterPort=2889
    volumes:
      - ./zoo2/data:/data
      - ./zoo2/datalog:/datalog

  zoo3:
    image: *zk-image
    restart: always
    container_name: zoo3
    ports:
      - "2183:2181"
      - "2890:2888"
      - "3890:3888"
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 observerMasterPort=2889
    volumes:
      - ./zoo3/data:/data
      - ./zoo3/datalog:/datalog

  observer:
    image: *zk-image
    restart: always
    container_name: observer
    ports:
      - "2184:2181"
      - "2891:2888"
      - "3891:3888"
    environment:
      - ZOO_MY_ID=4
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888 server.4=observer:2888:3888:observer observerMasterPort=2889 peerType=observer
    volumes:
      - ./observer/data:/data
      - ./observer/datalog:/datalog
