apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    workshop: ch05
spec:
  containers:
    - name: first-container
      image: nginx:1.21.5-alpine
    - name: second-container
      image: ubuntu
      command:
        - /bin/bash
        - -ec
        - while :; do echo "."; sleep 5; done