apiVersion: v1
kind: Pod
metadata:
  name: command-pod
  labels:
    workshop: ch05
spec:
  containers:
    - name: container-with-command
      image: alpine
      command:
        - /bin/sh
        - -c
        - while :; do echo '.'; sleep 5; done