version: '3.8'
services:
  sshd1:
    build: 
      context: .
      dockerfile: Dockerfile-sshd1
    ports:
      - 2222:22
    networks:
      - my-network
  ubuntu1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - my-network

networks:
  my-network: