version: '3'
services:
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    container_name: grafana
    depends_on:
      - prometheus
  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    volumes:
      - prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus