global:
  scrape_interval: 10s
scrape_configs:
  - job_name: example
    static_configs:
      - targets:
        - host.docker.internal:8000
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090