apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      run: kuard
  replicas: 2
  template:
    metadata:
      labels:
        run: kuard
      annotations:
        kubernetes.io/change-cause: "Update to green kuard"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuard-demo/kuard-amd64:green
        imagePullPolicy: Always
