kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: hello-kiamol
  labels:
    kiamol: ch15
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-kiamol
            port: 
              number: 80