CREATE ROLE dbz WITH LOGIN REPLICATION PASSWORD 'dbz';

GRANT CONNECT ON DATABASE appdb TO dbz;

\c appdb

CREATE TABLE IF NOT EXISTS public.items (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  qty INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT USAGE ON SCHEMA public TO dbz;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dbz;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dbz;

CREATE PUBLICATION dbz_pub FOR TABLE public.items;
