apiVersion: v1
kind: Service
metadata:
  name: numbers-api
spec:
  ports:
    - port: 80
  selector:
    app: lab-numbers-api
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lab-numbers-web
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: lab-numbers-web
    version: v1
  type:
    LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: lab-numbers-web-v2
spec:
  ports:
    - port: 8088
      targetPort: 80
  selector:
    app: lab-numbers-web
    version: v2
  type:
    LoadBalancer