apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  labels:
    kiamol: ch07-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      initContainers:
        - name: init-1
          image: kiamol/ch03-sleep
          command: ['sh', '-c', "echo '#!/bin/sh\necho test' > /init/startup.sh"]
          volumeMounts:
            - mountPath: "/init"
              name: init
        - name: init-2
          image: kiamol/ch03-sleep
          command: ['sh', '-c', 'chmod +x /init/startup.sh']
          volumeMounts:
            - mountPath: "/init"
              name: init
      containers:
        - name: web
          image: kiamol/ch05-pi
          command: ["/init/startup.sh"]
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: "/init"
              name: init
      volumes:
        - name: init
          emptyDir: {}